/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CloudHostingRouteImport } from './routes/cloud-hosting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as LinuxResellerHostingRouteImport } from './routes/linux-reseller-hosting'
import { Route as MicrosoftMailRouteImport } from './routes/microsoft-mail'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SiteLockRouteImport } from './routes/site-lock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SslCertificateRouteImport } from './routes/ssl-certificate'
import { Route as WebsiteBackupRouteImport } from './routes/website-backup'
import { Route as WindowsResellerHostingRouteImport } from './routes/windows-reseller-hosting'
import { Route as ZohoMailRouteImport } from './routes/zoho-mail'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudHostingRoute = CloudHostingRouteImport.update({
  id: '/cloud-hosting',
  path: '/cloud-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const LinuxResellerHostingRoute = LinuxResellerHostingRouteImport.update({
  id: '/linux-reseller-hosting',
  path: '/linux-reseller-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftMailRoute = MicrosoftMailRouteImport.update({
  id: '/microsoft-mail',
  path: '/microsoft-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteLockRoute = SiteLockRouteImport.update({
  id: '/site-lock',
  path: '/site-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SslCertificateRoute = SslCertificateRouteImport.update({
  id: '/ssl-certificate',
  path: '/ssl-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteBackupRoute = WebsiteBackupRouteImport.update({
  id: '/website-backup',
  path: '/website-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowsResellerHostingRoute = WindowsResellerHostingRouteImport.update({
  id: '/windows-reseller-hosting',
  path: '/windows-reseller-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ZohoMailRoute = ZohoMailRouteImport.update({
  id: '/zoho-mail',
  path: '/zoho-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/auth': typeof AuthRoute
  '/cloud-hosting': typeof CloudHostingRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/linux-reseller-hosting': typeof LinuxResellerHostingRoute
  '/microsoft-mail': typeof MicrosoftMailRoute
  '/services': typeof ServicesRoute
  '/site-lock': typeof SiteLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ssl-certificate': typeof SslCertificateRoute
  '/website-backup': typeof WebsiteBackupRoute
  '/windows-reseller-hosting': typeof WindowsResellerHostingRoute
  '/zoho-mail': typeof ZohoMailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/auth': typeof AuthRoute
  '/cloud-hosting': typeof CloudHostingRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/linux-reseller-hosting': typeof LinuxResellerHostingRoute
  '/microsoft-mail': typeof MicrosoftMailRoute
  '/services': typeof ServicesRoute
  '/site-lock': typeof SiteLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ssl-certificate': typeof SslCertificateRoute
  '/website-backup': typeof WebsiteBackupRoute
  '/windows-reseller-hosting': typeof WindowsResellerHostingRoute
  '/zoho-mail': typeof ZohoMailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/auth': typeof AuthRoute
  '/cloud-hosting': typeof CloudHostingRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/linux-reseller-hosting': typeof LinuxResellerHostingRoute
  '/microsoft-mail': typeof MicrosoftMailRoute
  '/services': typeof ServicesRoute
  '/site-lock': typeof SiteLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ssl-certificate': typeof SslCertificateRoute
  '/website-backup': typeof WebsiteBackupRoute
  '/windows-reseller-hosting': typeof WindowsResellerHostingRoute
  '/zoho-mail': typeof ZohoMailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/auth'
    | '/cloud-hosting'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/linux-reseller-hosting'
    | '/microsoft-mail'
    | '/services'
    | '/site-lock'
    | '/sitemap.xml'
    | '/ssl-certificate'
    | '/website-backup'
    | '/windows-reseller-hosting'
    | '/zoho-mail'
    | '/admin'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/auth'
    | '/cloud-hosting'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/linux-reseller-hosting'
    | '/microsoft-mail'
    | '/services'
    | '/site-lock'
    | '/sitemap.xml'
    | '/ssl-certificate'
    | '/website-backup'
    | '/windows-reseller-hosting'
    | '/zoho-mail'
    | '/admin'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-solutions'
    | '/auth'
    | '/cloud-hosting'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/linux-reseller-hosting'
    | '/microsoft-mail'
    | '/services'
    | '/site-lock'
    | '/sitemap.xml'
    | '/ssl-certificate'
    | '/website-backup'
    | '/windows-reseller-hosting'
    | '/zoho-mail'
    | '/_authenticated/admin'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  AuthRoute: typeof AuthRoute
  CloudHostingRoute: typeof CloudHostingRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  HostingRoute: typeof HostingRoute
  LinuxResellerHostingRoute: typeof LinuxResellerHostingRoute
  MicrosoftMailRoute: typeof MicrosoftMailRoute
  ServicesRoute: typeof ServicesRoute
  SiteLockRoute: typeof SiteLockRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SslCertificateRoute: typeof SslCertificateRoute
  WebsiteBackupRoute: typeof WebsiteBackupRoute
  WindowsResellerHostingRoute: typeof WindowsResellerHostingRoute
  ZohoMailRoute: typeof ZohoMailRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-hosting': {
      id: '/cloud-hosting'
      path: '/cloud-hosting'
      fullPath: '/cloud-hosting'
      preLoaderRoute: typeof CloudHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linux-reseller-hosting': {
      id: '/linux-reseller-hosting'
      path: '/linux-reseller-hosting'
      fullPath: '/linux-reseller-hosting'
      preLoaderRoute: typeof LinuxResellerHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft-mail': {
      id: '/microsoft-mail'
      path: '/microsoft-mail'
      fullPath: '/microsoft-mail'
      preLoaderRoute: typeof MicrosoftMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-lock': {
      id: '/site-lock'
      path: '/site-lock'
      fullPath: '/site-lock'
      preLoaderRoute: typeof SiteLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssl-certificate': {
      id: '/ssl-certificate'
      path: '/ssl-certificate'
      fullPath: '/ssl-certificate'
      preLoaderRoute: typeof SslCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-backup': {
      id: '/website-backup'
      path: '/website-backup'
      fullPath: '/website-backup'
      preLoaderRoute: typeof WebsiteBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/windows-reseller-hosting': {
      id: '/windows-reseller-hosting'
      path: '/windows-reseller-hosting'
      fullPath: '/windows-reseller-hosting'
      preLoaderRoute: typeof WindowsResellerHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoho-mail': {
      id: '/zoho-mail'
      path: '/zoho-mail'
      fullPath: '/zoho-mail'
      preLoaderRoute: typeof ZohoMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  AuthRoute: AuthRoute,
  CloudHostingRoute: CloudHostingRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  HostingRoute: HostingRoute,
  LinuxResellerHostingRoute: LinuxResellerHostingRoute,
  MicrosoftMailRoute: MicrosoftMailRoute,
  ServicesRoute: ServicesRoute,
  SiteLockRoute: SiteLockRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SslCertificateRoute: SslCertificateRoute,
  WebsiteBackupRoute: WebsiteBackupRoute,
  WindowsResellerHostingRoute: WindowsResellerHostingRoute,
  ZohoMailRoute: ZohoMailRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
