/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/hosting': typeof HostingRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/contact'
    | '/digital-marketing'
    | '/hosting'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  HostingRoute: typeof HostingRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  HostingRoute: HostingRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
